// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSXHWAjVetgkq3EPsOmGxL-x2tSicSG2w',
    appId: '1:30391450292:web:007420ab948e5716da75e1',
    messagingSenderId: '30391450292',
    projectId: 'myapp-flutter-firebase-one',
    authDomain: 'myapp-flutter-firebase-one.firebaseapp.com',
    storageBucket: 'myapp-flutter-firebase-one.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDknIQT8q50RsSMHVAdCfONEpw7Rq6byzs',
    appId: '1:30391450292:android:def9fb64850a344ada75e1',
    messagingSenderId: '30391450292',
    projectId: 'myapp-flutter-firebase-one',
    storageBucket: 'myapp-flutter-firebase-one.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjAagrB1ftTs8D1Z3aTm5ARhbc9jWxQQ0',
    appId: '1:30391450292:ios:18e320458ea0df78da75e1',
    messagingSenderId: '30391450292',
    projectId: 'myapp-flutter-firebase-one',
    storageBucket: 'myapp-flutter-firebase-one.firebasestorage.app',
    iosBundleId: 'com.hemanth.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjAagrB1ftTs8D1Z3aTm5ARhbc9jWxQQ0',
    appId: '1:30391450292:ios:18e320458ea0df78da75e1',
    messagingSenderId: '30391450292',
    projectId: 'myapp-flutter-firebase-one',
    storageBucket: 'myapp-flutter-firebase-one.firebasestorage.app',
    iosBundleId: 'com.hemanth.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSXHWAjVetgkq3EPsOmGxL-x2tSicSG2w',
    appId: '1:30391450292:web:20f20f93496005cdda75e1',
    messagingSenderId: '30391450292',
    projectId: 'myapp-flutter-firebase-one',
    authDomain: 'myapp-flutter-firebase-one.firebaseapp.com',
    storageBucket: 'myapp-flutter-firebase-one.firebasestorage.app',
  );
}
